language: erlang
script: "make"
notifications:
  irc: "irc.freenode.org#banane"
  recipients:
    - olivier@biniou.info
    on_success: change
    on_failure: always
otp_release:
  - 17.3
  - 17.1
  - 17.0
